# Generated by Django 5.2 on 2025-04-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtamaDetayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('tasarim_kodu', models.CharField(max_length=50)),
                ('proje_adi', models.CharField(max_length=100)),
                ('optimize_sure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Calisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('yetkinlik_seviyesi', models.PositiveSmallIntegerField()),
                ('tecrube_yili', models.FloatField()),
                ('verimlilik_puani', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GenetikSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senaryo', models.CharField(choices=[('normal', 'Normal'), ('kritik', 'Kritik')], max_length=10)),
                ('kayit_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaguchiSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasarim_kodu', models.CharField(max_length=50, unique=True)),
                ('optimum_sure', models.FloatField()),
                ('optimum_seviye', models.PositiveSmallIntegerField()),
                ('iyilestirme_orani', models.FloatField()),
                ('method', models.CharField(max_length=100)),
                ('departman', models.CharField(max_length=50)),
                ('guncellenme_tarihi', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TasarimKodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('urun_adi', models.CharField(max_length=150)),
                ('tahmini_montaj_suresi', models.FloatField()),
                ('minimum_yetkinlik_seviyesi', models.PositiveSmallIntegerField()),
                ('optimum_yetkinlik_seviyesi', models.PositiveSmallIntegerField()),
                ('ortalama_uretim_adedi', models.PositiveIntegerField()),
                ('zorluk_derecesi', models.PositiveSmallIntegerField()),
                ('departman', models.CharField(max_length=100)),
                ('ustabasi', models.PositiveSmallIntegerField(default=0)),
                ('kalifiyeli', models.PositiveSmallIntegerField(default=0)),
                ('cirak', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AtamaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('ustabasi', 'Ustabaşı'), ('kalifiyeli', 'Kalifiye'), ('cirak', 'Çırak')], max_length=20)),
                ('atama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calisanlar', to='cizelgeleme.atamadetayi')),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
            ],
        ),
        migrations.CreateModel(
            name='GenetikAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(max_length=20)),
                ('atanma_tipi', models.CharField(choices=[('atanan', 'Atanan'), ('alternatif', 'Alternatif')], max_length=20)),
                ('uygunluk_orani', models.FloatField(blank=True, null=True)),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
                ('sonuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='cizelgeleme.genetiksonuc')),
            ],
        ),
        migrations.CreateModel(
            name='PerformansDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('is_id', models.PositiveIntegerField()),
                ('tasarim_kodu', models.CharField(max_length=50)),
                ('proje_adi', models.CharField(max_length=100)),
                ('seviye', models.CharField(max_length=20)),
                ('is_kalitesi', models.FloatField()),
                ('sure_yonetimi', models.FloatField()),
                ('is_birligi', models.FloatField()),
                ('problem_cozme', models.FloatField()),
                ('teknik_yetkinlik', models.FloatField()),
                ('ortalama_puan', models.FloatField()),
                ('notlar', models.TextField(blank=True, null=True)),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
            ],
        ),
        migrations.AddField(
            model_name='genetiksonuc',
            name='tasarim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cizelgeleme.tasarimkodu'),
        ),
        migrations.AlterUniqueTogether(
            name='genetiksonuc',
            unique_together={('tasarim', 'senaryo')},
        ),
    ]
