# Generated by Django 5.2 on 2025-04-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortalama_performans', models.FloatField()),
                ('risk_skoru', models.FloatField()),
                ('gecikme_olasiligi', models.FloatField()),
                ('performans_kararliligi', models.FloatField()),
                ('simulasyon_zamani', models.DateTimeField()),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
            ],
        ),
        migrations.CreateModel(
            name='MonteCarloTasarimSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ortalama', models.FloatField()),
                ('risk_skoru', models.FloatField()),
                ('gecikme_olasiligi', models.FloatField()),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
                ('tasarim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.tasarimkodu')),
            ],
        ),
    ]
