# Generated by Django 5.2 on 2025-04-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0002_montecarlosonuc_montecarlotasarimsonuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GecmisPerformansVerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verimlilik_puani', models.FloatField()),
                ('proje_index', models.PositiveIntegerField(help_text='Geçmiş projeyi temsil eden sıra numarası')),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
                ('tasarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cizelgeleme.tasarimkodu')),
            ],
        ),
    ]
