# Generated by Django 5.2 on 2025-04-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0003_gecmisperformansverisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GecmisSureVerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman', models.CharField(max_length=100)),
                ('urun_adi', models.CharField(max_length=150)),
                ('sure', models.PositiveIntegerField()),
                ('kayit_index', models.PositiveIntegerField()),
                ('tasarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cizelgeleme.tasarimkodu')),
            ],
        ),
    ]
