# Generated by Django 5.2 on 2025-04-23 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0004_gecmissureverisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Is',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_adi', models.CharField(max_length=150)),
                ('teslimat_tarihi', models.DateField()),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('tamamlandi', 'Tamamlandı')], max_length=50)),
                ('oncelik', models.CharField(choices=[('normal', 'Normal'), ('acil', 'Acil')], max_length=50)),
                ('kalan_sure', models.FloatField()),
                ('tasarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cizelgeleme.tasarimkodu')),
            ],
        ),
        migrations.CreateModel(
            name='IsAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye', models.CharField(choices=[('ustabasi', 'Ustabaşı'), ('kalifiyeli', 'Kalifiyeli'), ('cirak', 'Çırak')], max_length=20)),
                ('calisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cizelgeleme.calisan')),
                ('is_objesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atananlar', to='cizelgeleme.is')),
            ],
        ),
    ]
