# Generated by Django 5.2 on 2025-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0005_is_isatama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='oncelik',
            field=models.CharField(choices=[('normal', 'Normal'), ('kritik', 'Kritik')], max_length=50),
        ),
    ]
