# Generated by Django 5.2 on 2025-06-09 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0006_alter_is_durum_alter_is_oncelik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='is_birligi',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='is_id',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='is_kalitesi',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='ortalama_puan',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='problem_cozme',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='proje_adi',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='seviye',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='sure_yonetimi',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='tasarim_kodu',
        ),
        migrations.RemoveField(
            model_name='performansdegerlendirme',
            name='teknik_yetkinlik',
        ),
        migrations.AddField(
            model_name='performansdegerlendirme',
            name='degerlendirme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performansdegerlendirme',
            name='is_degerlendirmesi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degerlendirmeler', to='cizelgeleme.is'),
        ),
        migrations.AddField(
            model_name='performansdegerlendirme',
            name='puan',
            field=models.PositiveSmallIntegerField(default=5, help_text='Çalışanın bu işteki performansı (1-10 arası)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performansdegerlendirme',
            name='notlar',
            field=models.TextField(blank=True, help_text='Bu değerlendirme ile ilgili ek notlar', null=True),
        ),
    ]
