# Generated by Django 5.2 on 2025-06-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0007_remove_performansdegerlendirme_is_birligi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performansdegerlendirme',
            name='calisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cizelgeleme.calisan'),
        ),
        migrations.AlterField(
            model_name='performansdegerlendirme',
            name='is_degerlendirmesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='cizelgeleme.is'),
        ),
    ]
