# Generated by Django 5.2 on 2025-06-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0008_alter_performansdegerlendirme_calisan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is',
            name='oncelik',
            field=models.CharField(choices=[('normal', 'Normal'), ('kritik', 'Kritik')], default='normal', max_length=50),
        ),
    ]
