# Generated by Django 5.2 on 2025-06-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cizelgeleme', '0009_alter_is_oncelik'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='taseron_cirak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Bu işe atanan taşeron çırak sayısı'),
        ),
        migrations.AddField(
            model_name='is',
            name='taseron_kalifiyeli',
            field=models.PositiveSmallIntegerField(default=0, help_text='Bu işe atanan taşeron kalifiyeli sayısı'),
        ),
        migrations.AddField(
            model_name='is',
            name='taseron_ustabasi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Bu işe atanan taşeron ustabaşı sayısı'),
        ),
    ]
